# Generated by Django 2.2.7 on 2019-11-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rfid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('idalumno', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'rfid',
            },
        ),
    ]
