# Generated by Django 2.2.7 on 2019-11-20 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('idalumno', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'asistencia',
            },
        ),
    ]
